### ISSUE TITLE
Any planning to merge from Avalon-Benchmark/godot to upstream godot?

### ISSUE THREAD

**Issue by lloydchang** [Avalon-Benchmark/avalon#23]
Hi Avalon-Benchmark Avalon team,

Is there planning to:

• Create future pull requests to merge from [Avalon-Benchmark/godot](https://github.com/Avalon-Benchmark/godot) to [upstream godot](https://github.com/godotengine/godot)?

• If yes, is there a roadmap summarizing the direction of how [Avalon-Benchmark/godot](https://github.com/Avalon-Benchmark/godot) would merge into [upstream godot](https://github.com/godotengine/godot)?

• If not, how would one report issues for [Avalon-Benchmark/godot](https://github.com/Avalon-Benchmark/godot) custom branches, such as `3.4.4-avalon`, without an "Issues" section?

For example: I am posting here in [Avalon-Benchmark: avalon](https://github.com/Avalon-Benchmark/avalon) because there isn't an "Issues" section in [Avalon-Benchmark: godot](https://github.com/Avalon-Benchmark/godot)

• If not, how often does [Avalon-Benchmark/godot](https://github.com/Avalon-Benchmark/godot) pull from [upstream godot](https://github.com/godotengine/godot) and resolve merge conflicts?

• A strategy with open source is to send pull requests upstream as early as possible to lower the maintenance burden of owning a fork drifting farther and farther away from upstream.

Thank you.

**Comment by mx781** [comment]
Hey @lloydchang - our changes to the Godot engine are quite Avalon-specific and not necessarily ones that make sense to live upstream. Godot 4.0 is also around the corner, and making Avalon compatible with a whole new major release would be a huge piece of work without much use for the benchmark (since we are not planning to add major new features at this point). In short, Avalon will probably stay fixed to our fork of Godot for the time being. 

Are you planning to build on top of our Godot wrapper and are looking for features available in later versions? Or are you having issues with the Godot side of Avalon? Happy to take a look if you share some more details.

**Comment by lloydchang** [comment]
Hi @mx781,

Thanks for getting back to me 🙂

My question was asked out of curiosity.

At this time, I do not plan to build on the Godot wrapper.

Since you answered my question, I am closing this issue.

Take care, and thank you!
